language: python
python:
  - "2.7"
before_install:
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3E5C1192
  - sudo bash -c 'echo "deb http://79.172.49.99/debian/ squeeze main" >> /etc/apt/sources.list'
  - sudo apt-get update
  - sudo apt-get install -f
  - sudo apt-get install libavformat53 libavformat-extra-53
  - sudo apt-get install libavcodec53 libavcodec-extra-53
  - sudo apt-get install libopencore-amrnb0 libopencore-amrwb0 libopencore-amrnb-dev libopencore-amrwb-dev zlib1g zlib1g-dev x264 libmp3lame0 flvtool2
  - sudo apt-get install ffmpeg
  - sudo apt-get install -t squeeze -y --force-yes $(apt-cache --no-generate pkgnames ooobasis3.4 | tr '\n' ' ')
  - sudo apt-get install -t squeeze -y --force-yes openoffice.org-ure $(apt-cache --no-generate pkgnames openoffice.org3 | tr '\n' ' ')
  - avconv -codecs
  - sudo ln -s /usr/lib/i386-linux-gnu/libz.so /usr/lib/
  - file -C -m ./magic
  - sudo npm install -g less
  - wget https://raw.github.com/mediasite/openoffice-wrapper/master/oowrapper.py
  - chmod +x ./oowrapper.py
  - sudo mv ./oowrapper.py /bin/
install:
  - pip install -r requirements/basic.txt
  - pip install -r requirements/dev.txt
  - pip install -r requirements/workers.txt
script: nosetests
