language: python
python:
  - "2.7"
services: 
  - mongodb
  - rabbitmq
before_install:
  - sudo bash -c 'echo "deb http://79.172.49.99/debian/ squeeze main" >> /etc/apt/sources.list'
  - sudo apt-get update
  - sudo apt-get install -t squeeze -y --force-yes $(apt-cache --no-generate pkgnames ooobasis3.4 | tr '\n' ' ')
  - sudo apt-get install -t squeeze -y --force-yes openoffice.org-ure $(apt-cache --no-generate pkgnames openoffice.org3 | tr '\n' ' ')
  - sudo apt-get install --force-yes flvtool2 nodejs
  - sudo npm install -g less@1.3.3
  - wget https://raw.github.com/mediasite/openoffice-wrapper/master/oowrapper.py
  - chmod +x ./oowrapper.py
  - sudo mv ./oowrapper.py /bin/
  - cp ./settings_test.py ./settings_local.py
  - wget http://79.172.49.99/ffmpeg/ffmpeg.static.32bit.2013-04-22.tar.gz -O /tmp/ffmpeg.tar.gz
  - sudo tar xvfp /tmp/ffmpeg.tar.gz -C /usr/bin/
install:
  - pip install --use-mirrors -r requirements/basic.txt
  - pip install --use-mirrors -r requirements/dev.txt
  - python ./manage.py compile_libmagic_db
  - python ./manage.py compile_avconv_db
  - python ./manage.py check_avconv_codecs
script:
  - python ./manage.py test_cov
