DEBUG = True
TESTING = True

SENTRY_DSN = None
SERVER_NAME = None

MONGO_HOST = '192.168.33.30'
MONGO_DB_NAME = 'grid_fs_test'
MONGO_REPLICATION_ON = False

BROKER_HOSTS = ['192.168.33.40:5672']
BROKER_USERNAME = 'guest'
BROKER_PASSWORD = 'guest'
BROKER_VHOST = '/'
